version: '3.8'

services:
  app:
    container_name: party-wall
    build:
      context: .
      target: party-wall # only build this part of the Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # 'hack' prevents node_modules/ in the container from being overridden
    working_dir: /usr/src/app
    command: npm run test:e2e
    environment:
      NODE_ENV: test
    networks:
      - testnet
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - testnet
    environment:
      POSTGRES_DB: party-wall
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PG_DATA: /var/lib/postgresql/data
    # volumes:
    # - ./seed.db.sql:/docker-entrypoint-initdb.d/db.sql <- run only once when the pgdata volume is first created (when run via docker-compose)
    # - pgdata:/var/lib/postgresql/data # or specify a local folder like ./docker-volumes/pgdata:/var/lib/postgresql/data

networks:
  testnet:

volumes:
  pgdata:
  logs:
